### ISSUE TITLE
[META] Byzantium implementation progress

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4050]
States: not started, in progress, implementation done, tests ready
---
**Create blockhash precompiled**
- [x] [EIP96](https://github.com/ethereum/EIPs/pull/210) implementation done https://github.com/ethereum/cpp-ethereum/pull/4066

---
**Remove medstate from receipts**
- [x] [EIP98](https://github.com/ethereum/EIPs/issues/98) implementation done  https://github.com/ethereum/cpp-ethereum/pull/4035
  - [x] does no affect consensus tests
---
**Change difficulty adjustment to target mean block time including uncles**
- [x] [EIP100](https://github.com/ethereum/EIPs/issues/100) implementation done https://github.com/ethereum/cpp-ethereum/pull/4017
  - [x] tests: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1197466216
---
**Draft EIP for the REVERT**
- [x] [EIP140](https://github.com/ethereum/EIPs/pull/206) implementation done
  - [x] tests: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=83032010
---
**Precompiled contract for pairing/elliptic curve operations**
- [x] [EIP196](https://github.com/ethereum/EIPs/pull/212) implementation done https://github.com/ethereum/cpp-ethereum/pull/3587
  - [x] tests: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=941134795
- [x] [EIP197](https://github.com/ethereum/EIPs/pull/213) implementation done https://github.com/ethereum/cpp-ethereum/pull/3587
  - [x] tests: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=941134795
---
**Create bigint_modexp**
- [x] [EIP198](https://github.com/ethereum/EIPs/pull/198) implementation done https://github.com/ethereum/cpp-ethereum/pull/4028 https://github.com/ethereum/cpp-ethereum/pull/4278
  - [x] tests: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1139401929
---
**RETURNDATACOPY and RETURNDATASIZE**
- [x] [EIP211](https://github.com/ethereum/EIPs/pull/211) implementation done https://github.com/ethereum/cpp-ethereum/issues/3611 (waiting for decision about out-of-range reads)
  - [x] tests: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1605675414
---
**New opcode: STATICCALL**
- [x] [EIP214](https://github.com/ethereum/EIPs/pull/214) implementation done https://github.com/ethereum/cpp-ethereum/pull/4057
  - [x] tests: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1412823514

**Comment by pirapira** [comment]
**Status Code in Transaction Receipt**

* [ ] [EIP 658](https://github.com/ethereum/EIPs/pull/658/files) implementation

**Comment by pirapira** [comment]
** Splitting Metropolis **

* [ ] Splitting Metropolis into two, deferring account abstraction https://github.com/ethereum/cpp-ethereum/issues/4268

**Comment by pirapira** [comment]
*Moving EIP-96 from Byzantium to Constantinople*

* [ ] moving EIP 96 into Constantinople

**Comment by pirapira** [comment]
**Diffuculty Bomb Delay**

* [ ] implementing [EIP649](https://github.com/ethereum/EIPs/pull/669)

**Comment by chfast** [comment]
Should we also split this issue into two new meta issues?

**Comment by pirapira** [comment]
That's a good idea in principle.  All tick boxes in this issue somehow modify the Byzantium behavior, so this issue can be reused as the Byzantium meta issue.

**Comment by chfast** [comment]
Yes, good. You can edit the description here.

**Comment by chfast** [comment]
@winsvega Can you update tests status on this?
