### ISSUE TITLE
Improve database interface

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4669]
We want this to be able to experiment with different database engines. Currently we use leveldb, but want to try rocksdb, lmdb and sqlite.

The current interface is a mixture of inheritance and template implicit interfaces and is "defined" in MemoryDB.h:
```
class MemoryDB
{
public:
	void clear() { m_main.clear(); m_aux.clear(); }	// WARNING !!!! didn't originally clear m_refCount!!!
	std::unordered_map<h256, std::string> get() const;

	std::string lookup(h256 const& _h) const;
	bool exists(h256 const& _h) const;
	void insert(h256 const& _h, bytesConstRef _v);
	bool kill(h256 const& _h);
	void purge();

	bytes lookupAux(h256 const& _h) const;
	void removeAux(h256 const& _h);
	void insertAux(h256 const& _h, bytesConstRef _v);

	h256Hash keys() const;
};
```
and OverlayDB.h:
```
class OverlayDB: public MemoryDB
{
public:
	ldb::DB* db() const { return m_db.get(); }

	void commit();
	void rollback();

	std::string lookup(h256 const& _h) const;
	bool exists(h256 const& _h) const;
	void kill(h256 const& _h);

	bytes lookupAux(h256 const& _h) const;
};
```

You can spot some problems imminently:
1. Virtual methods not used.
2. leveldb handle is leaked. 

## Tasks

- [ ] Define proper polymorphic interface for database.
- [ ] Implement MemoryDB as a simple wrapper of `std::unordered_map`.
- [ ] Use MemoryDB for tests.
- [ ] Implement LevelDB wrapper hiding leveldb includes.
- [ ] Implement OverlayDB using MemoryDB and LevelDB composition.

**TODO**: Specify concurrency requirements.

**Comment by gumb0** [comment]
Concurrency requirements roughly - all public methods should be thread-safe?
but I'll take later a closer look on how it's used

**Comment by gumb0** [comment]
leaked leveldb handle looks to be not used

**Comment by chfast** [comment]
Right: https://github.com/ethereum/cpp-ethereum/pull/4693.

**Comment by chfast** [comment]
One more thing in this subject. Usage of `bytes` being `std::vector<byte>` instead of `std::string` lowers our compatibility with external libs and also disables short string optimization.
